Repository Amazing-Favorites/Amazing-Favorites, pull requests merged in 2021-09, with the labels that each got.

#141 Notification center
  src/.editorconfig
  src/Newbe.BookmarkManager.Tests/ShowWhatNewJobTest.cs
  src/Newbe.BookmarkManager/Components/AfUserNotification.razor
  src/Newbe.BookmarkManager/Components/CloudSyncButtons/GoogleLoginButton.razor
  src/Newbe.BookmarkManager/Components/CloudSyncButtons/ManualySync.razor
  src/Newbe.BookmarkManager/Components/CloudSyncButtons/MicrosoftLogin.razor
  src/Newbe.BookmarkManager/Components/ManagePageNotificationService.cs
  src/Newbe.BookmarkManager/Components/ManagerButton.cs
  src/Newbe.BookmarkManager/Components/ManagerButton.razor
  src/Newbe.BookmarkManager/Components/NotificationCenter.cs
  src/Newbe.BookmarkManager/Components/NotificationCenter.razor
  src/Newbe.BookmarkManager/Components/NotificationCenterTemplates/CloudBkTokenExpired.razor
  src/Newbe.BookmarkManager/Components/NotificationCenterTemplates/NewReleaseMessage.razor
  src/Newbe.BookmarkManager/Components/NotificationCenterTemplates/NormalMessage.razor
  src/Newbe.BookmarkManager/Components/NotificationCenterTemplates/PinyinTokenExpired.razor
  src/Newbe.BookmarkManager/Components/NotificationCenterTemplates/PrivacyAgreementUpdatedMessage.razor
  src/Newbe.BookmarkManager/Components/NotificationCenterTemplates/SuccessToSyncBkWithCloud.razor
  src/Newbe.BookmarkManager/Components/NotificationCenterTemplates/SyncDataWithCloud.razor
  src/Newbe.BookmarkManager/Components/NotificationCenterTemplates/WelcomeMessage.razor
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/EventHubs/AfEventHub.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/NewNotificationEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/TriggerOpenControlPanelEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/UserNotificationEvent.cs
  src/Newbe.BookmarkManager/Services/Job/IInviteAcceptPrivacyAgreementJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/InviteAcceptPrivacyAgreementJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/JobHost.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/ShowWelcomeJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/ShowWhatNewJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudStatusCheckJob.cs
  src/Newbe.BookmarkManager/Services/Models/NotificationRecord.cs
  src/Newbe.BookmarkManager/Services/Services/ICloudServiceFactory.cs
  src/Newbe.BookmarkManager/Services/Services/INewNotification.cs
  src/Newbe.BookmarkManager/Services/Services/INotificationRecordService.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/CloudServiceFactory.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/NewNotification.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/NotificationRecordService.cs
  src/Newbe.BookmarkManager/Services/SimpleData/Entites/CloudBkSyncStatics.cs
  src/Newbe.BookmarkManager/Services/SimpleData/Entites/NotificationCenterStatus.cs
  src/Newbe.BookmarkManager/_Imports.razor
  src/Newbe.BookmarkManager/wwwroot/appsettings.json
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: 🌟 New Feature, size/XXL

#147 Issue fix & improving
  src/Newbe.BookmarkManager.Tests/ShowWhatNewJobTest.cs
  src/Newbe.BookmarkManager/Components/AfAddScript.cs
  src/Newbe.BookmarkManager/Components/TagInput.razor
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj
  src/Newbe.BookmarkManager/Pages/Background.cs
  src/Newbe.BookmarkManager/Pages/Background.razor
  src/Newbe.BookmarkManager/Pages/JsModuleLoader.cs
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Common/JsonHelper.cs
  src/Newbe.BookmarkManager/Services/EventHubs/AfEventHub.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/TriggerEditBookmarkEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/UserClickAfIconEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/IAfEventHandler.cs
  src/Newbe.BookmarkManager/Services/Job/IHandleUserClickIconJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/HandleUserClickIconJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/JobHost.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudStatusCheckJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncTagRelatedBkCountJob.cs
  src/Newbe.BookmarkManager/Services/Services/BookmarkApiExtensions.cs
  src/Newbe.BookmarkManager/Services/SimpleData/Entites/LastUserClickIconTabData.cs
  src/Newbe.BookmarkManager/_Imports.razor
  src/Newbe.BookmarkManager/wwwroot/appsettings.json
  src/Newbe.BookmarkManager/wwwroot/content/background_keyboard.js
  src/Newbe.BookmarkManager/wwwroot/content/manager_keyboard.js
  src/Newbe.BookmarkManager/wwwroot/content/popup.js
  src/Newbe.BookmarkManager/wwwroot/index.html
Labels: size/XL, 🐞 Bug Fix

#150 Upgrade version
  src/Newbe.BookmarkManager/Components/ControlPanel.razor
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/NotificationRecordService.cs
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: size/S, skip-changelog

#152 Change AfEventHub with Storage API
  src/Newbe.BookmarkManager/Services/EventHubs/AfEventHub.cs
  src/Newbe.BookmarkManager/wwwroot/content/popup.js
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: size/M, skip-changelog

#155 Fix/one drive cors
  src/Newbe.BookmarkManager/Services/Common/MicrosoftTokenInvalidException.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudJob.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/OneDriveClient.cs
Labels: size/S

#157 Revert "Fix/one drive cors"
  src/Newbe.BookmarkManager/Services/Common/MicrosoftTokenInvalidException.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudJob.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/OneDriveClient.cs
Labels: size/S

#146 Feature/omnibox suggest
  src/Newbe.BookmarkManager/Components/ControlPanel.razor
  src/Newbe.BookmarkManager/Components/ControlSubPanel/OmniboxSuggestPanel.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/UserOptionSaveEvent.cs
  src/Newbe.BookmarkManager/Services/Job/IHandleOmniBoxSuggestJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/HandleOmniBoxSuggestJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/JobHost.cs
  src/Newbe.BookmarkManager/Services/Models/UserOptions.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/UserOptionsService.cs
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: 🌟 New Feature, size/L

#168 Fix: it can`t sync data to OneDrive or GoogleCloud when there is no NewbeApi access token is set
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudJob.cs
Labels: 🐞 Bug Fix, size/XS

#169 Add sharing button in edit dialog
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
Labels: size/XS
