Repository Amazing-Favorites/Amazing-Favorites, pull requests merged in 2021-11, with the labels that each got.

#193 Keeping a consistent application ID during development.
  src/Newbe.BookmarkManager/wwwroot/manifest.json
  src/browserextension.pem
Labels: size/S, 🛠 Improvement

#181 Support to search from omnibox
  src/Newbe.BookmarkManager.Tests/SmallCacheTest.cs
  src/Newbe.BookmarkManager.Tests/SuggestResultDescriptionBuilderTest.cs
  src/Newbe.BookmarkManager/Components/BkHistory.razor
  src/Newbe.BookmarkManager/Components/ControlPanel.razor
  src/Newbe.BookmarkManager/Components/ControlSubPanel/OmniboxSuggestPanel.razor
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Common/ISmallCache.cs
  src/Newbe.BookmarkManager/Services/Common/Impl/SmallCache.cs
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/SmallCacheExpiredEvent.cs
  src/Newbe.BookmarkManager/Services/Job/IBkSearcherServerJob.cs
  src/Newbe.BookmarkManager/Services/Job/IHandleOmniBoxSuggestJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/BkSearcherServerJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/HandleOmniBoxSuggestJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/JobHost.cs
  src/Newbe.BookmarkManager/Services/LPC/ILPCServer.cs
  src/Newbe.BookmarkManager/Services/LPC/LPCServer.cs
  src/Newbe.BookmarkManager/Services/LPC/LPCServerExtensions.cs
  src/Newbe.BookmarkManager/Services/MessageBus/BusExtensions.cs
  src/Newbe.BookmarkManager/Services/MessageBus/Impl/Bus.cs
  src/Newbe.BookmarkManager/Services/Models/UserOptions.cs
  src/Newbe.BookmarkManager/Services/Repository/Impl/IndexedDbRepo.cs
  src/Newbe.BookmarkManager/Services/Servers/BkSearcherServer.cs
  src/Newbe.BookmarkManager/Services/Servers/IBkSearcherServer.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/IndexedBkSearcher.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/UserOptionsService.cs
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: 🌟 New Feature, size/XL

#201 add check list
  src/Newbe.BookmarkManager/README.md
  src/Newbe.BookmarkManager/wwwroot/content/manifest_prod.json
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: size/S, skip-changelog

#202 add more image
  README.md
Labels: size/S, skip-changelog

#205 upgrade dotnet version
  .github/workflows/dotnet-format.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/release_test.yml
Labels: size/XS

#209 Feature/changeDefaultSort
  src/Newbe.BookmarkManager.Tests/Newbe.BookmarkManager.Tests.csproj
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Ai/Events.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncBookmarkJob.cs
  src/Newbe.BookmarkManager/Services/Models/Bk.cs
  src/Newbe.BookmarkManager/Services/Models/SearchResultItem.cs
  src/Newbe.BookmarkManager/Services/Services/IBkManager.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/IndexedBkManager.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/IndexedBkSearcher.cs
Labels: size/L
