Repository Amazing-Favorites/Amazing-Favorites, pull requests merged in 2021-08, with the labels that each got.

#73 Add github action to test publish with AOT
  .github/workflows/test-publish.yml
  src/Directory.Build.props
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj
Labels: size/M

#75 UI enhancement
  .github/workflows/release.yml
  src/Directory.Build.props
  src/Newbe.BookmarkManager/Components/BkEditForm.cs
  src/Newbe.BookmarkManager/Components/BkEditForm.razor
  src/Newbe.BookmarkManager/Components/HotTags.razor
  src/Newbe.BookmarkManager/Components/LikeProject.razor
  src/Newbe.BookmarkManager/Components/TagInput.razor
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj
  src/Newbe.BookmarkManager/Pages/Background.cs
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/wwwroot/content/background_keyboard.js
  src/Newbe.BookmarkManager/wwwroot/content/manager_keyboard.js
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: size/L, 🛠 Improvement

#81 Ready to release 0.6
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: size/XS

#82 Add Application Insight
  src/Newbe.BookmarkManager/App.razor
  src/Newbe.BookmarkManager/Components/ControlPanel.razor
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj
  src/Newbe.BookmarkManager/Pages/Background.cs
  src/Newbe.BookmarkManager/Pages/JsModuleLoader.cs
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Ai/AiLoggerProvider.cs
  src/Newbe.BookmarkManager/Services/Ai/ApplicationInsightAop.cs
  src/Newbe.BookmarkManager/Services/Ai/ApplicationInsightsLogger.cs
  src/Newbe.BookmarkManager/Services/Ai/InsightAttribute.cs
  src/Newbe.BookmarkManager/Services/Models/UserOptions.cs
  src/Newbe.BookmarkManager/Services/Services/IBkManager.cs
  src/Newbe.BookmarkManager/Services/Services/IBkSearcher.cs
  src/Newbe.BookmarkManager/Services/Services/ICloudService.cs
  src/Newbe.BookmarkManager/Services/Services/IUserOptionsService.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/IndexedBkManager.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/IndexedBkSearcher.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/UserOptionsService.cs
  src/Newbe.BookmarkManager/Services/TextAlias/TextAliasProviderBase.cs
  src/Newbe.BookmarkManager/_Imports.razor
  src/Newbe.BookmarkManager/wwwroot/content/ai.js
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: 🌟 New Feature, size/XL

#96 Fix first use tag are not unique
  .github/workflows/main.yml
  src/Newbe.BookmarkManager/Services/Services/Impl/IndexedBkManager.cs
Labels: 🐞 Bug Fix, size/XS

#100 Update main.yml
  .github/workflows/main.yml
Labels: size/XS, skip-changelog

#106 Support to show WhatsNew when version changed
  src/.editorconfig
  src/Newbe.BookmarkManager.Tests/AfCodeServiceTest.cs
  src/Newbe.BookmarkManager.Tests/ShowWhatNewJobTest.cs
  src/Newbe.BookmarkManager.Tests/UrlHashServiceTest.cs
  src/Newbe.BookmarkManager.WebApi/Program.cs
  src/Newbe.BookmarkManager/Components/ControlPanel.razor
  src/Newbe.BookmarkManager/Components/LikeProject.razor
  src/Newbe.BookmarkManager/Pages/Background.cs
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Ai/Events.cs
  src/Newbe.BookmarkManager/Services/Common/WebHelper.cs
  src/Newbe.BookmarkManager/Services/Configuration/StaticUrlOptions.cs
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/Job/IShowWhatNewJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/ShowWhatNewJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncAliasJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncBookmarkJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncTagRelatedBkCountJob.cs
  src/Newbe.BookmarkManager/Services/Models/AfMetadata.cs
  src/Newbe.BookmarkManager/Services/Models/SearchResultItem.cs
  src/Newbe.BookmarkManager/Services/Services/IBkManager.cs
  src/Newbe.BookmarkManager/Services/Services/IBkSearcher.cs
  src/Newbe.BookmarkManager/Services/Services/ICloudService.cs
  src/Newbe.BookmarkManager/Services/Services/IUserOptionsService.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/AfCodeService.cs
  src/Newbe.BookmarkManager/Services/Services/TabsApiExtensions.cs
  src/Newbe.BookmarkManager/Services/TextAlias/ITextAliasProvider.cs
  src/Newbe.BookmarkManager/Services/View/BkEditFormData.cs
  src/Newbe.BookmarkManager/wwwroot/appsettings.json
Labels: size/XL

#107 Support to Show User Privacy Agreement Change Notification
  src/Newbe.BookmarkManager/Components/ControlPanel.razor
  src/Newbe.BookmarkManager/Components/DevButtons.razor
  src/Newbe.BookmarkManager/Components/IManagePageNotificationService.cs
  src/Newbe.BookmarkManager/Components/ManagePageNotificationService.cs
  src/Newbe.BookmarkManager/Pages/Background.cs
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Configuration/DevOptions.cs
  src/Newbe.BookmarkManager/Services/Configuration/StaticUrlOptions.cs
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncAliasJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudJob.cs
  src/Newbe.BookmarkManager/Services/Models/UserOptions.cs
  src/Newbe.BookmarkManager/wwwroot/appsettings.json
Labels: 🌟 New Feature, size/L

#108 Support to show Welcome when user install extension at the first time
  src/Newbe.BookmarkManager/Components/DevButtons.razor
  src/Newbe.BookmarkManager/Pages/Background.cs
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Ai/Events.cs
  src/Newbe.BookmarkManager/Services/Configuration/StaticUrlOptions.cs
  src/Newbe.BookmarkManager/Services/Job/IShowWelcomeJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/ShowWelcomeJob.cs
  src/Newbe.BookmarkManager/Services/Models/AfMetadata.cs
  src/Newbe.BookmarkManager/wwwroot/appsettings.json
Labels: 🌟 New Feature, size/L

#111 upgrade to pre7
  .github/workflows/dotnet-format.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: size/XS, skip-changelog

#112 fix dll hash
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: size/XS, skip-changelog

#117 Support to record and auto complete search history
  src/Newbe.BookmarkManager.Tests/WebHelperTest.cs
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Common/AccessTokenInvalidException.cs
  src/Newbe.BookmarkManager/Services/Common/WebHelper.cs
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/Models/BkViewItem.cs
  src/Newbe.BookmarkManager/Services/Models/RecentSearch.cs
  src/Newbe.BookmarkManager/Services/Models/SearchRecord.cs
  src/Newbe.BookmarkManager/Services/Services/IBkManager.cs
  src/Newbe.BookmarkManager/Services/Services/IRecentSearchHolder.cs
  src/Newbe.BookmarkManager/Services/Services/IRecordService.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/RecentSearchHolder.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/RecordService.cs
Labels: size/L, ⭐ Feature

#118 fix error when application insight disabled
  src/Directory.Build.props
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Ai/EmptyApplicationInsights.cs
Labels: size/L, 🐞 Bug Fix

#120 Support to sync your data by Google Drive
  src/Newbe.BookmarkManager/Components/AfUserNotification.razor
  src/Newbe.BookmarkManager/Components/ControlPanel.razor
  src/Newbe.BookmarkManager/Components/GoogleLogin.razor
  src/Newbe.BookmarkManager/Components/ManagePageNotificationService.cs
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj.DotSettings
  src/Newbe.BookmarkManager/Pages/Background.cs
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Common/JsonHelper.cs
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/EventHubs/AfEventEnvelope.cs
  src/Newbe.BookmarkManager/Services/EventHubs/AfEventHub.cs
  src/Newbe.BookmarkManager/Services/EventHubs/EventHandlerBase.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/GoogleBackgroundLoginResultEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/GoogleTryLoginInBackgroundEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/UserGoogleDriveLoginSuccessEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/UserNotificationEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/FuncEventHandler.cs
  src/Newbe.BookmarkManager/Services/EventHubs/IAfEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/IAfEventHandler.cs
  src/Newbe.BookmarkManager/Services/EventHubs/IAfEventHub.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudJob.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncTagRelatedBkCountJob.cs
  src/Newbe.BookmarkManager/Services/Models/RecentSearch.cs
  src/Newbe.BookmarkManager/Services/Models/SimpleDataEntity.cs
  src/Newbe.BookmarkManager/Services/Models/UserOptions.cs
  src/Newbe.BookmarkManager/Services/Services/ICloudServiceFactory.cs
  src/Newbe.BookmarkManager/Services/Services/IGoogleDriveClient.cs
  src/Newbe.BookmarkManager/Services/Services/IRecentSearchHolder.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/CloudServiceFactory.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/GoogleDriveClient.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/GoogleDriveCloudService.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/NewbeApiCloudService.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/RecentSearchHolder.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/TokenBaseInitializer.cs
  src/Newbe.BookmarkManager/Services/SimpleData/Entites/GoogleDriveStatics.cs
  src/Newbe.BookmarkManager/Services/SimpleData/Entites/RecentSearch.cs
  src/Newbe.BookmarkManager/Services/SimpleData/ISimpleData.cs
  src/Newbe.BookmarkManager/Services/SimpleData/ISimpleDataStorage.cs
  src/Newbe.BookmarkManager/Services/SimpleData/SimpleDataStorage.cs
  src/Newbe.BookmarkManager/wwwroot/appsettings.json
  src/Newbe.BookmarkManager/wwwroot/manifest.json
Labels: 🌟 New Feature, size/XXL

#124 Add OneDriveClient
  src/Newbe.BookmarkManager.sln
  src/Newbe.BookmarkManager/App.razor
  src/Newbe.BookmarkManager/Components/MicrosoftLogin.razor
  src/Newbe.BookmarkManager/GraphClientExtensions.cs
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Services/IOneDriveClient.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/OneDriveClient.cs
  src/Newbe.BookmarkManager/_Imports.razor
  src/Newbe.BookmarkManager/wwwroot/appsettings.json
  src/Newbe.BookmarkManager/wwwroot/content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js
  src/Newbe.BookmarkManager/wwwroot/index.html
Labels: size/L

#126 add OneDriveCloudService
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/MicrosoftBackgroundLoginResultEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/MicrosoftTryLoginInBackgroundEvent.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/UserOneDriveLoginSuccessEvent.cs
  src/Newbe.BookmarkManager/Services/Models/UserOptions.cs
  src/Newbe.BookmarkManager/Services/Services/IOneDriveClient.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/OneDriveClient.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/OneDriveCloudService.cs
Labels: size/L

#129 Better Control Panel
  src/Newbe.BookmarkManager/Components/ControlPanel.razor
  src/Newbe.BookmarkManager/Components/ControlSubPanel/ApplicationInsightPanel.razor
  src/Newbe.BookmarkManager/Components/ControlSubPanel/CloudBkPanel.razor
  src/Newbe.BookmarkManager/Components/ControlSubPanel/HotTagsPanel.razor
  src/Newbe.BookmarkManager/Components/ControlSubPanel/PinyinPanel.razor
  src/Newbe.BookmarkManager/Components/ControlSubPanel/SystemActionsPanel.razor
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/TriggerResumeFactorySettingEvent.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/RecentSearchHolder.cs
  src/Newbe.BookmarkManager/_Imports.razor
  src/Newbe.BookmarkManager/wwwroot/content/my-ant-design-blazor.css
  src/Newbe.BookmarkManager/wwwroot/index.html
Labels: 🛠 Improvement

#138 UI improve
  src/Newbe.BookmarkManager/Components/AfCodePanel.razor
  src/Newbe.BookmarkManager/Components/ControlPanel.razor
  src/Newbe.BookmarkManager/Components/ControlSubPanel/ApplicationInsightPanel.razor
  src/Newbe.BookmarkManager/Components/ControlSubPanel/HotTagsPanel.razor
  src/Newbe.BookmarkManager/Pages/Manager.razor
Labels: size/M

#139 Feature/notification
  src/Newbe.BookmarkManager/Components/ManagerButton.razor
  src/Newbe.BookmarkManager/Components/NotificationList.razor
  src/Newbe.BookmarkManager/Components/NotificationManager.razor
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj
  src/Newbe.BookmarkManager/Pages/Manager.cs
  src/Newbe.BookmarkManager/Program.cs
  src/Newbe.BookmarkManager/Services/Consts.cs
  src/Newbe.BookmarkManager/Services/EventHubs/Events/UserNotificationEvent.cs
  src/Newbe.BookmarkManager/Services/Job/Impl/SyncCloudStatusCheckJob.cs
  src/Newbe.BookmarkManager/Services/Models/NotificationRecord.cs
  src/Newbe.BookmarkManager/Services/Services/INotificationRecordService.cs
  src/Newbe.BookmarkManager/Services/Services/Impl/NotificationRecordService.cs
  src/Newbe.BookmarkManager/wwwroot/appsettings.json
Labels: size/L

#140 Update page header
  src/Newbe.BookmarkManager/Components/ManagerButton.cs
  src/Newbe.BookmarkManager/Components/ManagerButton.razor
  src/Newbe.BookmarkManager/Newbe.BookmarkManager.csproj
  src/Newbe.BookmarkManager/Pages/Manager.razor
  src/Newbe.BookmarkManager/wwwroot/content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js
  src/Newbe.BookmarkManager/wwwroot/index.html
Labels: size/L, 🛠 Improvement
